steps:

  # Validate Request number input
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate-request-number'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -z "$_REQUEST_NO" ]; then
          echo "❌ ERROR: _REQUEST_NO is required but was not provided, please provide it and Retry."
          exit 1
        fi
        echo "✅ _REQUEST_NO provided: $_REQUEST_NO"
        
  # install dependencies
  - name: 'python:3.10'
    entrypoint: pip
    args: ["install", "-r", "IE/Composer/requirements.txt", "--user"]

  # run
  - name: 'python:3.10'
    entrypoint: python
    args:
      [
        "IE/Composer/add_dags_to_composer.py",
        "--dags_directory=${_DAGS_DIRECTORY}",
        "--test_dags_bucket=${_DAGS_BUCKET}",
        "--dags_bucket_subfolder=${_DAGS_BUKCET_SUBFOLDER}",
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x ./IE/Composer/sox.sh && \
        ./IE/Composer/sox.sh "$PROJECT_ID" $BUILD_ID  $COMMIT_SHA  $_IMAGE_NO  $_REQUEST_NO
logsBucket: ${_LOGS_BUCKET}
